### ISSUE TITLE
Analyzer fails to load projects with .net 9 rc.2.24474 installed alongside .net 6 & 8 (Windows)

### ISSUE THREAD

**Issue by marklam** [ionide/FSharp.Analyzers.SDK#220]
**Describe the bug**
The analyzer command-line tool doesn't seem to like having .net 9 (pre-release) installed. Posting this in case it might also apply to .net9 release.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install the tool fsharp-analyzers  0.27.0 
2. Add `nuget Ionide.Analyzers` to paket.dependencies and do a `dotnet paket install`
3. `dotnet fsharp-analyzers --project wharever.fsproj --analyzers-path D:\Nuget\Packages\ionide.analyzers\0.12.0\analyzers\dotnet\fs --verbosity d`

**Expected behaviour**
Complaints about the state of my code.

**Error**
```
[10:33:47.339] info: Loading analyzers from d:\nuget\Packages\ionide.analyzers\0.12.0\analyzers\dotnet\fs
[10:33:47.354] info: Registered 12 analyzers from 1 dlls
[10:33:47.360] info: Loading project D:\Git\SpotMapMS.Analyzers\SpotMapMS\SpotMapMS.fsproj
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Ionide.ProjInfo.WorkspaceLoader.Ionide.ProjInfo.IWorkspaceLoader.LoadProjects(FSharpList`1 projects, FSharpList`1 customProperties, BinaryLogGeneration binaryLogs)
   at Program.loadProjects@133-2.Invoke(Unit unitVar) in /_//src/FSharp.Analyzers.Cli/Program.fs:line 134
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 510
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
--- End of stack trace from previous location ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 454
   at Microsoft.FSharp.Control.AsyncPrimitives.QueueAsyncAndWaitForResultSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1139
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1166
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1515
   at Program.results$cont@621(ToolsPath toolsPath, SeverityMappings severityMapping, FSharpList`1 projOpts, FSharpOption`1 fscArgs, FSharpChoice`2 exclInclFiles, FSharpList`1 properties, Client`2 client, Unit unitVar) in /_//src/FSharp.Analyzers.Cli/Program.fs:line 638
   at Program.main(String[] argv) in /_//src/FSharp.Analyzers.Cli/Program.fs:line 619
```

**Environment (please complete the following information):**
 - OS: Windows 11
 - fsharp-analyzers version: 0.27.0 
 - Ionide.Analyzers version: 0.12
 - dotnet SDK version:
```
>dotnet --list-sdks
6.0.427 [C:\Program Files\dotnet\sdk]
8.0.403 [C:\Program Files\dotnet\sdk]
9.0.100-rc.2.24474.11 [C:\Program Files\dotnet\sdk]

>dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 9.0.0-rc.2.24474.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 9.0.0-rc.2.24473.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 9.0.0-rc.2.24474.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]```
 - mono / .Net Framework version:

**Additional context**
Add any other context about the problem here.

**Comment by marklam** [comment]
Looks to be fixes with release of .net 9
