### ISSUE TITLE
Custom analyzer not working in 0.0.4

### ISSUE THREAD

**Issue by jovanhan2** [ionide/FSharp.Analyzers.SDK#3]
Hi, I'm working on a project that creates custom analyzers to improve error detection in FSharp following your tutorial [here](https://medium.com/lambda-factory/introducing-f-analyzers-772487889429)

I have a bracket analyzer that works under `FSharp.Analyzers.SDK = 0.0.1`, however when I upgrade to `FSharp.Analyzers.SDK = 0.04` the analyzer no longer works. 

For example, in SDK 0.0.1 I can generate and print out the context of the code in the Fsharp Language server logs:
```
ctx [|"// <auto-generated>";
  "//     Generated by the FSharp WriteCodeFragment class.";
  "// </auto-generated>"; "namespace FSharp"; ""; "open System";
  "open System.Reflection"; ""; "";
  "[<assembly: System.Reflection.AssemblyCompanyAttribute("SampleAnalyzerUsage")>]";
...
```

by writing 

```fsharp
[<Analyzer>]
let paranthesis : Analyzer =
    printfn "Inside custom analyzer!"
    
    fun ctx ->
        printfn "ctx %A" ctx.Content
       ....
```

In 0.0.4 only the `Inside custom analyzer!` appears, the context doesn't get called. I am using Ionide 3.33 - perhaps 0.04 requires the later version of Ionide? 

However in Ionide >= 3.34 I am having trouble registering the analyzers regardless of whether I'm using 0.0.1 of the SDK or 0.0.4 
```
Could not load type 'range' from assembly 'FSharp.Compiler.Service, Version=28.0.0.0, Culture=neutral, PublicKeyToken=null

(from the FSharp language service logs)
```

And 

```
[14:47:06 ERROR] RES (010) <- {registerAnalyzer} ERROR in 543 ms: {stack: Error: Request failed with status code 500
	at createError (C:\Users\Louis\.vscode\extensions\ionide.ionide-fsharp-3.36.2\fsharp.js:14130:15)
	at settle (C:\Users\Louis\.vscode\extensions\ionide.ionide-fsharp-3.36.2\fsharp.js:18695:12)
	at IncomingMessage.handleStreamEnd (C:\Users\Louis\.vscode\extensions\ionide.ionide-fsharp-3.36.2\fsharp.js:28146:11)
	at IncomingMessage.emit (events.js:187:15)
	at endReadableNT (_stream_readable.js:1090:12)
	at process._tickCallback (internal/process/next_tick.js:63:19), message: Request failed with status code 500, config: [object Object], request: [object Object], response: [object Object]} Data=undefined

From the FSharp Language Service (server)
```
Any help is greatly appreciated. Also please do let me know if I should head over to the ionide forums. 

Many thanks!

**Comment by Krzysztof-Cieslak** [comment]
> I am using Ionide 3.33 - perhaps 0.04 requires the later version of Ionide?

Yes, the version of SDK used by your analyzer must be the same as version used currently by Ionide/FSAC.

I'll try to investigate the problem tomorrow.
