### ISSUE TITLE
Current Analyzers CLI needs to bundle msbuild locator

### ISSUE THREAD

**Issue by baronfel** [ionide/FSharp.Analyzers.SDK#34]
**Describe the bug**
running the current (0.6.0) release of the analyzer cli fails with the following error:

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Program' threw an exception.
 ---> System.TypeInitializationException: The type initializer for '<StartupCode$FSharp-Analyzers-Cli>.$Program' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Locator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9dff12846e04bfbd'. The system cannot find the file specified.

File name: 'Microsoft.Build.Locator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9dff12846e04bfbd'
   at Ionide.ProjInfo.Init.init()
   at <StartupCode$FSharp-Analyzers-Cli>.$Program..cctor() in /Users/chethusk/oss/FSharp.Analyzers.SDK/src/FSharp.Analyzers.Cli/Program.fs:line 22
   --- End of inner exception stack trace ---
   at Program..cctor()
   --- End of inner exception stack trace ---
   at Program.main(String[] argv) in /Users/chethusk/oss/FSharp.Analyzers.SDK/src/FSharp.Analyzers.Cli/Program.fs:line 169
```

We need to bundle the locator with this tool, I believe.

**Comment by Krzysztof-Cieslak** [comment]
I've thought I've fixed this

**Comment by baronfel** [comment]
Oh, this is already done in latest master. @Krzysztof-Cieslak just need to push a new version I think.

**Comment by baronfel** [comment]
Jinx!
